# -*- coding: utf-8 -*-
"""inverted_pendulum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PENBSi2mj9KfvFKPHHVcz9qx76lBY1ct
"""

def inverted_pendulum(t, x):
    g = 9.8
    l = 1
    m = 1
    M = 1

    d1 = M + m * (1 - np.cos(x[1])**2)
    d2 = l * d1

    F = 0  # No input

    dxdt = np.zeros(4)
    dxdt[0] = x[2]
    dxdt[1] = x[3]
    dxdt[2] = (F + m * l * x[3]**2 * np.sin(x[1]) - m * g * np.sin(x[1]) * np.cos(x[1])) / d1
    dxdt[3] = (-F * np.cos(x[1]) - m * l * x[3]**2 * np.sin(x[1]) * np.cos(x[1]) + (M + m) * g * np.sin(x[1])) / d2

    return dxdt