# -*- coding: utf-8 -*-
"""tank_solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viFJz4TvlG_1ahi0DEEtIoTbjjnrc6zy
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Define tank model function
def tank_model(t, x):
    A = 1.0
    C = 2.0
    F_in = 0
    u = 0.1

    xp = 1/A * (F_in - C * u * np.sqrt(x))
    return xp

t_span = [0, 100]  # Simulation time from 0 to 10 seconds
x0 = [100]        # Initial tank level (example: starting at 0.5 units)

# Solve the ODE
sol = solve_ivp(tank_model, t_span, x0)

# Plotting the tank level over time
plt.plot(sol.t, sol.y[0])
plt.xlabel('Time (sec)')
plt.ylabel('Tank Level (units)')
plt.title('Tank Level Simulation')
plt.grid(True)
plt.show()