# -*- coding: utf-8 -*-
"""tank_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PYpakoWAxUODinO25FW74gghJLFSYsD
"""

# Define tank model function
def tank_model(t, x):
    A = 1.0
    C = 2.0
    F_in = 0
    u = 0.1

    xp = 1/A * (F_in - C * u * np.sqrt(x))
    return xp