# -*- coding: utf-8 -*-
"""ex6_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWwm72XFcUaRJjpULHAiYHpJJ30mw0XZ
"""

import numpy as np
from scipy.linalg import eig
from control import acker

# Define matrices
A = np.array([[0, 1, 0, 0], [0, 0, -9.8, 0], [0, 0, 0, 1], [0, 0, 19.6, 0]])
b = np.array([[0], [1], [0], [-1]])

# Compute eigenvalues of A
e = eig(A)[0]

# Desired pole locations
pd = [-4.43, -4.43, -2-2j, -2+2j]

# Pole placement using acker
k = acker(A, b, pd)

# Display results
print("Eigenvalues of A:\n", e)
print("Gain vector k:\n", k)