# -*- coding: utf-8 -*-
"""inverted_pendulum_k1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8oeJdHkG77AVqVFhmrIphWQY2D-VY3o
"""

import numpy as np

def inverted_pendulum_k1(t, x):
    # Constants
    g = 9.8
    l = 1
    m = 1
    M = 1

    # State feedback gains
    k = np.array([-16.0203, -15.2428, -98.6852, -28.1028])

    # Intermediate calculations
    d1 = M + m * (1 - np.cos(x[2]) ** 2)
    d2 = l * d1

    # State feedback
    F = -np.dot(k, x)

    # State derivatives
    xp = np.zeros(4)
    xp[0] = x[1]
    xp[1] = (F + m * l * x[3] ** 2 * np.sin(x[2]) - m * g * np.sin(x[2]) * np.cos(x[2])) / d1
    xp[2] = x[3]
    xp[3] = (-F * np.cos(x[2]) - m * l * x[3] ** 2 * np.sin(x[2]) * np.cos(x[2]) + (M + m) * g * np.sin(x[2])) / d2

    return xp