# -*- coding: utf-8 -*-
"""ex6_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bin3KQSn9DaPV2lTjfEfi4QxYsqc915r
"""

import numpy as np

# System matrices
A = np.array([[-2, -1, 2], [-1, -2, 2], [-2, 0, 2]])
B = np.array([[0, 0], [0, 1], [1, 0]])

# Vector f and b
f = np.array([[1], [1]])
b = B @ f

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
v = np.linalg.inv(eigenvectors)

# Projection
p = v[:2, :] @ b

# Display results
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Inverse of eigenvectors matrix:\n", v)
print("Projection:\n", p)