# -*- coding: utf-8 -*-
"""fig6_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o16VqdZb4Iy2ioogBamja2bYzAKoU9ZP
"""

import numpy as np
import matplotlib.pyplot as plt

# Define k values
k = np.arange(0.02, 5.02, 0.02)
x = np.array([1, 0])

# Calculate J1, J2, J3 for different values of r
r_values = [0, 1, 2]
J1 = []
J2 = []
J3 = []

for r in r_values:
    p11 = 0.5 / k + 0.5 + (r + 1) * k / 2 + r * k**2 / 2
    p12 = 0 / (5 * k) + r * k / 2
    p22 = 0.5 / k + 0.5 + r * k / 2
    J = p11 * x[0]**2 + 2 * p12 * x[0] * x[1] + p22 * x[1]**2
    if r == 0:
        J1 = J
    elif r == 1:
        J2 = J
    elif r == 2:
        J3 = J

# Plot J1, J2, J3
plt.figure(figsize=(10, 6))
plt.plot(k, J1, 'k', label='r=0', linewidth=2)
plt.plot(k, J2, '-.', color='black', label='r=1', linewidth=2)
plt.plot(k, J3, '--', color='black', label='r=2', linewidth=2)
plt.grid(True)
plt.xlabel('k')
plt.ylabel('J')
plt.legend()
plt.title('Cost Function J for Different Values of r')
plt.show()

# Plot J2 and J4
r = 2
x = np.array([0, 1])
p11 = 0.5 / k + 0.5 + (r + 1) * k / 2 + r * k**2 / 2
p12 = 0 / (5 * k) + r * k / 2
p22 = 0.5 / k + 0.5 + r * k / 2
J4 = p11 * x[0]**2 + 2 * p12 * x[0] * x[1] + p22 * x[1]**2

plt.figure(figsize=(10, 6))
plt.plot(k, J2, 'k', label='J2', linewidth=2)
plt.plot(k, J4, '-.', color='black', label='J4', linewidth=2)
plt.grid(True)
plt.xlabel('k')
plt.ylabel('J')
plt.legend()
plt.title('Comparison of Cost Functions J2 and J4')
plt.show()