# -*- coding: utf-8 -*-
"""DC_motor_w.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzstQqJXO0GyUoHn0iHuNm3-4d_R8JD-
"""

import numpy as np

def DC_motor_w(t, x):
    # State variable x=[theta, omega, i, Tl]
    A = np.array([[0, 1, 0, 0],
                  [0, 0, 4.438, -7.396],
                  [0, -12, -24, 0],
                  [0, 0, 0, -1]])

    B = np.array([[0, 0],
                  [0, -7.396],
                  [20, 0],
                  [0, 0]])

    k = np.array([3.0000, 0.8796, 0.1529, -1.8190])
    theta_d = 0           # Desired angular position
    Tl = 0.01             # Step disturbance

    v1 = 2.255 * Tl - k[0] * (x[0] - theta_d) - k[1] * x[1] - k[2] * x[2]
    v2 = 2.255 * Tl - np.dot(k, x)
    u = np.array([v1, Tl])

    xp = np.dot(A, x) + np.dot(B, u)

    return xp