# -*- coding: utf-8 -*-
"""CL_DCmotor_solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udvONx02pb5-lPjCu2QjGnU6WCsBI8zt
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def DC_motor(x, t):
    # Parameters and matrices from the MATLAB function
    A = np.array([[0, 1, 0],
                  [0, 0, 4.438],
                  [0, -12, -24]])

    B = np.array([[0, 0],
                  [0, -7.396],
                  [20, 0]])

    theta_d = 0           # Desired angular position
    Tl = 0.01             # Step disturbance
    v = 2.255 * Tl - 3.0 * (x[0] - theta_d) - 0.879 * x[1] - 0.1529 * x[2]
    u = np.array([v, Tl])

    xp = np.dot(A, x) + np.dot(B, u)
    return xp

# Initial conditions and time span
x0 = np.array([0.0, 0.0, 0.0])
t = np.linspace(0, 3, 301)  # Time points for integration

# Solve the ODE system
x = odeint(DC_motor, x0, t)

# Plot the results
plt.figure(figsize=(10, 6))
plt.plot(t, x[:, 0] * 180 / np.pi, 'k', linewidth=2)
plt.grid(True)
plt.xlabel('Time (sec)')
plt.ylabel('Angular displacement θ (degrees)')
plt.title('Angular Displacement of DC Motor')
plt.show()