# -*- coding: utf-8 -*-
"""ex6_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131gtUiUtTtSMvHaP3METezfE1tdr93GI
"""

import numpy as np
from scipy.linalg import eig
from scipy.signal import place_poles
import control
# Define matrices and vectors
A = np.array([[0, 1, 0, 0],
              [0, 0, -9.8, 0],
              [0, 0, 0, 1],
              [0, 0, 19.6, 0]])
b = np.array([[0],
              [1],
              [0],
              [-1]])

# Compute eigenvalues of A
e = eig(A)[0]
print("Eigenvalues of A:")
print(e)

# Desired pole locations (adjusted to avoid repeated poles)
pd = np.array([-4.43, -4.4, -2-2j, -2+2j])


k = control.acker(A, b, pd)
print("Gain matrix k:")
print(k)