# -*- coding: utf-8 -*-
"""DC_motor_LTR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QElNkQI1kkyBvsq8ndJ5mUz7m9uY-WQH
"""

import numpy as np
import scipy.linalg
from control import lqr, place

# Define the system matrices
A = np.array([[0, 1, 0, 0],
              [0, 0, 4.438, -7.396],
              [0, -12, -24, 0],
              [0, 0, 0, -1]])

B = np.array([[0],
              [0],
              [20],
              [0]])

C = np.array([[1, 0, 0, 0]])

# State feedback design using LQR
R = np.array([[1]])
Q1 = np.diag([9, 0, 0, 0])
K, _, _ = lqr(A, B, Q1, R)

# State observer design using pole placement
pd = np.array([-5-5j, -5+5j, -7+7j, -7-7j])
G = place(A.T, C.T, pd).T

# Print the results
print("State feedback gain matrix, K:")
print(K)
print("Observer gain matrix, G:")
print(G)