# -*- coding: utf-8 -*-
"""ex6_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HE0H9YLRCefCzc3LcBsP5FeWrDqJ70k5
"""

import numpy as np
from scipy.linalg import inv

# Define matrices
A = np.array([[0, 1, 0, 0], [0, 0, -9.8, 0], [0, 0, 0, 1], [0, 0, 19.6, 0]])
b = np.array([[0], [1], [0], [-1]])

# Controllability matrix
def ctrb(A, B):
    n = A.shape[0]
    C = B
    for i in range(1, n):
        C = np.hstack((C, np.linalg.matrix_power(A, i) @ B))
    return C

C = ctrb(A, b)

# Define vectors
a = np.array([0, -19.6, 0, 0])
alpha = np.array([12.86, 63.065, 149.38, 157.0])

# Psi_1 matrix
Psi_1 = np.array([
    [1, -a[0], a[0]**2 - a[1], -a[0]**3 + 2*a[0]*a[1] - a[2]],
    [0, 1, -a[0], a[0]**2 - a[1]],
    [0, 0, 1, -a[0]],
    [0, 0, 0, 1]
])

# Calculate k
k = (alpha - a) @ Psi_1 @ inv(C)

# Display result
print("Gain vector k:\n", k)