# -*- coding: utf-8 -*-
"""DC_motor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IZdcGCiUseKQ1WJv60qdjwEMGXITvDS
"""

import numpy as np

def DC_motor(t, x):
    # State variable x=[theta, omega, i]
    A = np.array([[0, 1, 0],
                  [0, 0, 4.438],
                  [0, -12, -24]])

    B = np.array([[0, 0],
                  [0, -7.396],
                  [20, 0]])

    theta_d = 0           # Desired angular position
    Tl = 0.01             # Step disturbance

    v = 2.255 * Tl - 3.0 * (x[0] - theta_d) - 0.879 * x[1] - 0.1529 * x[2]
    u = np.array([v, Tl])

    xp = np.dot(A, x) + np.dot(B, u)

    return xp