# -*- coding: utf-8 -*-
"""ex6_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_ROFjx4LS56lFoIRBJq8PIG0WgE3O13
"""

import numpy as np
import control

# Define the system matrices
A = np.array([[0, 1, 0, 0],
              [0, 0, -9.8, 0],
              [0, 0, 0, 1],
              [0, 0, 19.6, 0]])

b = np.array([[0], [1], [0], [-1]])

# Define the weighting matrices Q and R
Q = np.diag([4, 0, 8.16, 0])
R = 1 / 400

# Calculate the LQR gain matrix
k, _, _ = control.lqr(A, b, Q, R)

print("LQR gain matrix k:")
print(k)